version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - cafeteria-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fastapi_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cafeteria-network
    command: --default-authentication-plugin=mysql_native_password --skip-log-bin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=user
      - PMA_PASSWORD=password
      - UPLOAD_LIMIT=300M
    depends_on:
      - db
    networks:
      - cafeteria-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  cafeteria-network:
    driver: bridge